// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_Y5OHVtnd2GBT4ZynkVXVMfFRHGt2Bk',
    appId: '1:152483220026:web:f5c8a90cc7c0f470860303',
    messagingSenderId: '152483220026',
    projectId: 'rentnov',
    authDomain: 'rentnov.firebaseapp.com',
    storageBucket: 'rentnov.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMFl6DgBGGiUJcyVzwj2ODj66bWm1l-mg',
    appId: '1:152483220026:android:ab8911096ed8b4ec860303',
    messagingSenderId: '152483220026',
    projectId: 'rentnov',
    storageBucket: 'rentnov.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVTv7sLN_m7FK0LZw0foj0ABOPPlcKVW8',
    appId: '1:152483220026:ios:180e50b6713adfc2860303',
    messagingSenderId: '152483220026',
    projectId: 'rentnov',
    storageBucket: 'rentnov.firebasestorage.app',
    iosBundleId: 'com.example.rentnova',
  );
}
